INSERT INTO roles (name) SELECT 'CUSTOMER' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'CUSTOMER');
INSERT INTO roles (name) SELECT 'KITCHEN' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'KITCHEN');
INSERT INTO roles (name) SELECT 'DELIVERY' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'DELIVERY');
INSERT INTO roles (name) SELECT 'ADMIN' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ADMIN');

INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Cena Maridaje: Sidras de Espalme & Cortes Nobles', 'Un recorrido por 6 llagares históricos guiado por nuestra sumiller María Fernández, maridando cada paso con piezas singulares de goxu asturiano a baja temperatura.', '2026-03-28 20:30:00', '/events-img/events-pairing.jpeg', '18 plazas exclusivas', 75.00, TRUE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Cena Maridaje: Sidras de Espalme & Cortes Nobles');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Jornadas Gastronómicas del Chosco y la Carrillera', 'Tres días dedicados a la reinterpretación de dos grandes pilares de la cocina de montaña. Recetas tradicionales encontrándose con técnicas moleculares y texturas crujientes.', '2026-04-02 14:00:00', '/events-img/events-asturian-cured-pork-sausage.jpeg', 'Menú degustación 5 pases', 48.00, TRUE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Jornadas Gastronómicas del Chosco y la Carrillera');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Mesa Redonda: De la Dehesa al plato', 'Diálogo abierto entre criadores de goxu asturcelta, llagareros artesanales y nuestro equipo de cocina sobre la preservación de razas autóctonas y sostenibilidad rural.', '2026-04-24 19:00:00', '/events-img/events-panel-discussion.jpeg', 'Coloquio & Cóctel de cierre', NULL, TRUE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Mesa Redonda: De la Dehesa al plato');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Noche de Sidra Bajo las Estrellas', 'Cena al aire libre en nuestra terraza, con escanciado tradicional y música en directo de gaita asturiana.', '2026-06-15 21:00:00', '/events-img/events-pairing.jpeg', 'Terraza exterior', 55.00, FALSE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Noche de Sidra Bajo las Estrellas');
INSERT INTO events (title, description, event_date, image, details, price, featured) SELECT 'Vendimia y Sidra: Fiesta de la Cosecha', 'Celebración del cierre de temporada con productos de proximidad y una selección especial de sidras de la casa.', '2026-09-20 20:00:00', '/events-img/events-asturian-cured-pork-sausage.jpeg', 'Aforo limitado', 60.00, FALSE FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Vendimia y Sidra: Fiesta de la Cosecha');

/*
  PRODUCTOS (CARTA)
  Mismo patrón que roles y eventos: INSERT ... SELECT ... FROM DUAL WHERE NOT EXISTS.
  Así el script se puede ejecutar en cada arranque sin duplicar platos
  - La comprobación de "ya existe" se hace por el nombre del plato
  - image apunta a la carpeta public/menu-img/ del front
  - category usa exactamente las mismas palabras que las pestañas de CartaView
  - badge_label y badge_tone quedan a NULL en los platos sin etiqueta
*/
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Cachopo Tradicional', 'Dos tiernos filetes de ternera asturiana rellenos de jamón serrano reserva y queso de Pría fundido, empanado crujiente. Acompañado de patatas gajo.', 24.50, '/menu-img/cachopo-tradicional.png', 'Carnes', TRUE, TRUE, 'Recomendado', 'primary' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Cachopo Tradicional');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Fabada Asturiana', 'La auténtica fabada elaborada a fuego lento con faba de la Granja IGP y nuestro compango seleccionado (chorizo, morcilla y panceta ahumada).', 18.00, '/menu-img/fabada.png', 'Especialidades', TRUE, TRUE, 'Clásico', 'highlight' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Fabada Asturiana');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Arroz con Leche Réquexu', 'Cremoso y suave, requemado al momento con azúcar de caña. Una receta familiar transmitida de generación en generación.', 6.50, '/menu-img/arroz-con-leche.png', 'Postres', FALSE, FALSE, 'Postre', 'neutral' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Arroz con Leche Réquexu');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Croquetas de Jamón', 'Croquetas caseras cremosas de jamón ibérico, fritas al momento y de textura crujiente.', 9.50, '/menu-img/croquetas-jamon.png', 'Entrantes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Croquetas de Jamón');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Cochinillo Asado', 'Cochinillo asado lentamente hasta conseguir una piel crujiente y una carne jugosa y tierna.', 22.00, '/menu-img/cochinillo.png', 'Carnes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Cochinillo Asado');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Bao de Panceta', 'Pan bao esponjoso relleno de panceta confitada, encurtidos y salsa asturiana.', 12.00, '/menu-img/bao-panceta.png', 'Entrantes', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Bao de Panceta');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Tarta de Queso', 'Tarta de queso cremosa horneada al estilo tradicional, con un ligero toque caramelizado.', 7.00, '/menu-img/tarta-queso.png', 'Postres', TRUE, FALSE, 'Postre', 'neutral' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Tarta de Queso');
INSERT INTO products (name, description, price, image, category, available, featured, badge_label, badge_tone) SELECT 'Sidra Natural', 'Sidra natural asturiana DOP, servida escanciada al momento.', 8.00, '/menu-img/sidra.png', 'Bebidas', TRUE, FALSE, NULL, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name = 'Sidra Natural');